// Curated default curriculum themes seeded into the DB.
export const DEFAULT_THEMES = [
  {
    slug: "self-intro",
    title: "자기소개와 스몰토크",
    description: "처음 만났을 때 어색함을 푸는 일상 표현 — 인사, 직업, 취미, 가족.",
    level: "BEGINNER",
    emoji: "👋",
    bullets: [
      "기본 인사 / 존댓말 vs 반말",
      "본인 소개 (직업, 출신, 사는 곳)",
      "취미와 주말 일과",
      "가족 구성원 표현",
      "헤어질 때 인사 패턴",
    ].join("\n"),
  },
  {
    slug: "kfood",
    title: "한국 음식과 식문화",
    description: "식당에서 주문하기, 매운 정도 설명, 한국식 회식 매너.",
    level: "BEGINNER",
    emoji: "🍱",
    bullets: [
      "식당에서 주문 패턴",
      "맛 표현 (매콤하다, 짭짤하다)",
      "음식 호불호 묻기",
      "회식 / 술자리 매너",
      "배달 앱 사용 표현",
    ].join("\n"),
  },
  {
    slug: "kpop-kdrama",
    title: "K-Pop / K-Drama 토크",
    description: "최애 아이돌, 좋아하는 드라마를 한국어로 설명하기.",
    level: "INTERMEDIATE",
    emoji: "🎤",
    bullets: [
      "최애(최고로 애정) 표현",
      "노래/드라마 추천하기",
      "감상평 (감동적이다, 몰입했다)",
      "팬덤 용어 — 덕질, 입덕, 탈덕",
      "콘서트 / 굿즈 관련 표현",
    ].join("\n"),
  },
  {
    slug: "travel-korea",
    title: "한국 여행 회화",
    description: "공항, 택시, 호텔, 길 묻기 등 여행자에게 가장 유용한 패턴.",
    level: "BEGINNER",
    emoji: "✈️",
    bullets: [
      "공항 / 입국 심사",
      "지하철, 버스, 택시 이용",
      "호텔 체크인 / 문제 해결",
      "길 묻기 / 방향 안내 받기",
      "여행지 추천 받기",
    ].join("\n"),
  },
  {
    slug: "business-korean",
    title: "비즈니스 한국어",
    description: "회의, 이메일 인사, 명함 교환, 호칭 — 직장에서 바로 쓰는 표현.",
    level: "ADVANCED",
    emoji: "💼",
    bullets: [
      "직급/호칭 (대리님, 과장님)",
      "이메일 인사 / 마무리 표현",
      "회의 의견 제시 패턴",
      "명함 주고 받기",
      "협상 시 부드러운 거절 표현",
    ].join("\n"),
  },
  {
    slug: "daily-life",
    title: "일상 생활 표현",
    description: "병원, 은행, 마트, 미용실 — 한국에서 살 때 부딪치는 생활 회화.",
    level: "INTERMEDIATE",
    emoji: "🏙️",
    bullets: [
      "병원 예약 / 증상 설명",
      "은행 / 체크카드 만들기",
      "마트에서 가격 묻기",
      "미용실에서 원하는 스타일 설명",
      "공과금 / 임대 관련 표현",
    ].join("\n"),
  },
  {
    slug: "slang",
    title: "젊은 세대 슬랭과 신조어",
    description: "JMT, 갓생, 킹받네 — 친구처럼 자연스럽게 말하기.",
    level: "ADVANCED",
    emoji: "🔥",
    bullets: [
      "최근 1~2년 유행 신조어",
      "줄임말 패턴 (얼죽아, 만반잘부)",
      "온라인 채팅 표현",
      "리액션 표현 (대박, 진짜, 헐)",
      "세대별로 다른 어휘 비교",
    ].join("\n"),
  },
  {
    slug: "free-talk",
    title: "자유 주제 (튜터 추천)",
    description: "튜터가 학습자 레벨에 맞춰 그날의 주제를 즉흥적으로 선정.",
    level: "INTERMEDIATE",
    emoji: "🎲",
    bullets: [
      "학습자가 미리 알려주는 토픽",
      "튜터가 즉석에서 제안",
      "최근 뉴스 한 토막",
      "한국 vs 본국 문화 비교",
    ].join("\n"),
  },
] as const;
